In [76]:
import numpy as np
import time

In [77]:
py_list = list(range(1000000))
start = time.time()
sq_list = [i ** 2 for i in py_list]
end = time.time()
print("Python list time:", end - start)

np_array = np.array(py_list)
start = time.time()
#vectorization
sq_array = np_array ** 2
end = time.time()
print("Numpy list time:", end - start)

Python list time: 0.30507397651672363
Numpy list time: 0.01001739501953125


In [78]:
#memory

import sys

print("python list size:", {sys.getsizeof(py_list) * len(py_list)}, "bytes")
print("python list size:", {np_array.nbytes}, "bytes")


python list size: {8000056000000} bytes
python list size: {8000000} bytes


In [79]:
arr1 = np.array([1,2,3,4,5])
print(arr1.shape)

arr2 = np.array([1,2,3,'Prasad'])
print(arr2)
print(( arr2.dtype ))

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(arr2d.shape)

(5,)
['1' '2' '3' 'Prasad']
<U21
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [80]:
#create
arr1 = np.zeros((2,3), dtype=int) # includes all zeros
print(arr1)

arr2 = np.full((2,3), 10) # includes all tens
print(arr2)

arr3 = np.eye((3)) #identity matrix - diagonal elements are 1
print(arr3)

arr4 = np.arange(1,11,2) # start end stop like a normal range fnc
print(arr4)

arr5 = np.linspace(1,100,3) # evely spaced array
print(arr5)


[[0 0 0]
 [0 0 0]]
[[10 10 10]
 [10 10 10]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[  1.   50.5 100. ]


In [81]:
#properties of numpy array
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape) #dimensions mxn

print(arr.size) #total elements
print(arr.dtype) # datatype
print(arr.ndim) # no of dimensions

float_arr = arr.astype(np.float64)
print(float_arr)


(2, 3)
6
int64
2
[[1. 2. 3.]
 [4. 5. 6.]]


In [82]:
#operations on arrays

arr = np.array([[1,2,3],[4,5,6]]) 
print(arr.shape)

reshaped = arr.reshape((3,2)) 
print(reshaped)

flattened = arr.flatten()
print(flattened)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [83]:
# indexing
arr = np.array([[1,2,3],[4,5,6]]) 
print(arr[0][1])

#fancy indexing
arr = np.array([10,20,30,40,50])
indices = [1,3,4]
print(arr[indices])

#boolean indexing
arr = np.array([10,15,20,25,30])
check = arr > 20
print(arr[check])

2
[20 40 50]
[25 30]


In [84]:
#slicing

arr = np.array([10,20,30,40,50])
print(arr[1 : 3])
print(arr[1 :])
print(arr[: 3])
print(arr[:])
print(arr[::2])


[20 30]
[20 30 40 50]
[10 20 30]
[10 20 30 40 50]
[10 30 50]


In [85]:
nums = [10,20,30,40,50]
sub_arr = nums[1:3]
sub_arr[1] = 100
print(nums)
print(sub_arr)
arr = np.array([10,20,30,40,50])
sub_arr = arr[1:3].copy()
sub_arr[1] = 100
print(arr)
print(sub_arr)


[10, 20, 30, 40, 50]
[20, 100]
[10 20 30 40 50]
[ 20 100]


In [86]:
# axes in multidimensional arrays

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

sum_of_rows = np.sum(arr2d, axis = 1)
sum_of_cols  = np.sum(arr2d, axis = 0)
print("Sum of rows:", sum_of_rows)
print("Sum of columns:", sum_of_cols)

#slicing 2d array
print(arr2d[0:2, 1:2])  #rows 0 and 1, columns 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of rows: [ 6 15 24]
Sum of columns: [12 15 18]
[[2]
 [5]]


In [107]:
arr = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr, arr.shape)

#indexing
print(arr[0,2,1])
print(arr[1,2,0])

#slicing
print(arr[:, 0, 1])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
6
11
[2 8]


In [111]:
# verctorization 
arr = np.array([1,2,3,4,5,6])

print(arr ** 2)
print(arr + 10)

[ 1  4  9 16 25 36]
[11 12 13 14 15 16]


In [114]:
# broadcasting

## scaling array without using extra space
arr = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6]])
print(arr + arr2)


[[ 2  4  6  8 10 12]
 [ 2  4  6  8 10 12]]


In [118]:
# vector normalization

arr = np.array([[1,2], [3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)
print("Mean : ", mean)
print("Std: ", std_dev)

normalized_arr = (arr - mean) / std_dev
print("Normalized array:\n", normalized_arr)
mean = np.mean(normalized_arr)
std_dev = np.std(normalized_arr)
print("Mean : ", mean)
print("Std: ", std_dev)

Mean :  2.5
Std:  1.118033988749895
Normalized array:
 [[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
Mean :  0.0
Std:  1.0


In [121]:
# aggerigation functions
arr = np.array([1,2,3,4,5])

print("Sum:", np.sum(arr))
print("Prod:", np.prod(arr))
print("min:", np.min(arr))
print("max:", np.max(arr))
print("std:", np.std(arr))
print("var:", np.var(arr))
print("median:", np.median(arr))
print("argMin:", np.argmin(arr))
print("argmax:", np.argmax(arr))


Sum: 15
Prod: 120
min: 1
max: 5
std: 1.4142135623730951
var: 2.0
median: 3.0
argMin: 0
argmax: 4


In [123]:
# power functions
arr = np.array([1,2,3,4,5])

print("Square root:", np.sqrt(arr))
print("Square:", np.square(arr))
print("Pow:", np.power(arr, 2))

Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Square: [ 1  4  9 16 25]
Pow: [ 1  4  9 16 25]


In [125]:
# log functions

arr = np.array([1,2,3,4,5])

print("log : ", np.log(arr))
print("log2 : ", np.log2(arr))
print("log10 : ", np.log10(arr))
print("exp : ", np.exp(arr))

log :  [0.         0.69314718 1.09861229 1.38629436 1.60943791]
log2 :  [0.         1.         1.5849625  2.         2.32192809]
log10 :  [0.         0.30103    0.47712125 0.60205999 0.69897   ]
exp :  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [127]:
# rounding

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

arr = np.array([1,2,3,4,5,-1,-2,-3,1,2,3])
print(np.abs(arr))
print(np.unique(arr))
print(np.sort(arr))

3.0
4.0
3.0
3.0
[1 2 3 4 5 1 2 3 1 2 3]
[-3 -2 -1  1  2  3  4  5]
[-3 -2 -1  1  1  2  2  3  3  4  5]
